name: 'Website builds everywhere'

on:
  pull_request:

jobs:
  RunJobs:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"

    - name: 'Init'
      run: dotnet fsi amsite.fsx init

    - name: 'Build'
      run: dotnet fsi amsite.fsx build

    - name: 'Clean'
      run: dotnet fsi amsite.fsx clean

    - name: 'Uninit'
      run: dotnet fsi amsite.fsx uninit
