name: Website deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'preview'

    - name: Initialize
      run: dotnet fsi amsite.fsx init

    - name: Generate
      run: dotnet fsi amsite.fsx build

    - uses: JamesIves/github-pages-deploy-action@v4
      name: Publish on Github Pages
      with:
        branch: gh-pages
        folder: .output/final
