name: Website deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Initialize
      run: |
         dotnet fsi amsite.fsx init
   
    - name: Generate
      run: |
        dotnet fsi amsite.fsx build
        ls -la
        ls -la .output
        ls -la .output/final
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources/AngouriMath/AngouriMath/bin/release/netstandard2.0
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources/AngouriMath/AngouriMath/bin/release
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources/AngouriMath/AngouriMath/bin
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources/AngouriMath/AngouriMath
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources/AngouriMath
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath/Sources
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src/AngouriMath
        ls /home/runner/work/AngouriMathSite/AngouriMathSite/src
        ls /home/runner/work/AngouriMathSite/AngouriMathSite
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: Publish on Github Pages
      with:
        branch: gh-pages
        folder: .output/final
