name: Website deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Clone AngouriMath (1/3)
      run: |
        cd _generator
        git clone https://github.com/asc-community/AngouriMath AngouriMath
      
    - name: Clone Yadg.NET (2/3)
      run: |
        cd _generator
        git clone https://github.com/WhiteBlackGoose/Yadg.NET Yadg.NET
      
    - name: Clone Wiki (3/3)
      run: |
        cd _generator/content
        git clone https://github.com/asc-community/AngouriMath.wiki.git _wiki
      
    - name: Build AngouriMath
      run: |
        cd _generator/AngouriMath/Sources/AngouriMath
        dotnet build AngouriMath.csproj -c release  
    
    - name: Run Generator
      run: |
        cd _generator/NaiveStaticGenerator
        dotnet run -c release
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: Publish on Github Pages
      with:
        branch: gh-pages
        folder: ./generated
